CSCI465v5old/firstapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'page2$',views.page2, name='page2'),
    url(r'register/$',views.register, name='register'),
    url(r'suggestions/$',views.suggestions, name='suggestions'),
    url(r'^suggest/$',views.suggestion_view, name='suggest'),
    url(r'profile/$',views.profile, name='profile'),
    url(r'about/$',views.about, name='about'),
    url(r'lfg/$',views.lfg, name='lfg'),
    url(r'lfm/$',views.lfm, name='lfm'),
    url(r'wtb/$',views.wtb, name='wtb'),
    url(r'wts/$',views.wts, name='wts'),

]

CSCI465v5old/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views
from firstapp.forms import LoginForm

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'login/$', views.login, {
        'template_name':'login.html',
        'authentication_form':LoginForm
    }, name="login"),
    url(r'logout/$', views.logout,{
        'next_page':'/login'
    }),
    url(r'',include('firstapp.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSCI465v5old/firstapp/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
CHOICES = (('LFG', 'Lfg',), ('LFM', 'Lfm',),('WTB', 'Wtb',), ('WTS', 'Wts',))
class suggestion(models.Model):
    suggestion = models.CharField(max_length=141)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    authored = models.DateTimeField(auto_now=True)
    # LFG = 'Lfg'
    # LFM = 'Lfm'
    # WTB = 'Wtb'
    # WTS = 'Wts'
    # CHOICES = ((LFG, 'Lfg',), (LFM, 'Lfm',),(WTB, 'Wtb',), (WTS, 'Wts',))
    choice_field = models.CharField(max_length=3, choices=CHOICES,default='LFG')
    image = models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d/')
    idescription = models.CharField(max_length=144)
    def __str__(self):
        return self.suggestion

class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(null=True, max_length=500, blank=True)
    games = models.CharField(null=True, max_length=140, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    # def __str__(self):
    #     return self.profile

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

CSCI465v5old/firstapp/forms.py
from django import forms
from django.core.validators import validate_unicode_slug
from firstapp.models import CHOICES
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import *

class suggestion_form(forms.Form):
    suggestion = forms.CharField(label='Post Title', max_length=140)
    image=forms.ImageField(label="Image File")
    # CHOICES = (('LFG', 'Lfg',), ('LFM', 'Lfm',),('WTS', 'Wtb',), ('WTS', 'Wts',))
    choice_field = forms.ChoiceField(widget=forms.Select(), choices=CHOICES)
    image_description=forms.CharField(label="Image Description", max_length=144)

    def save(self, request , commit=True):
        suggest = suggestion()
        suggest.suggestion=self.cleaned_data['suggestion']
        suggest.choice_field=self.cleaned_data['choice_field']
        suggest.image=self.cleaned_data['image']
        suggest.idescription=self.cleaned_data['image_description']
        suggest.author=request.user
        if commit:
            suggest.save()
        return suggest
    # work in progress
    # CHOICES = (('1', 'LFG',), ('2', 'LFM',), ('3', 'WTB',), ('4', 'WTS',))
    # choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)

class LoginForm(AuthenticationForm):
    username=forms.CharField(
        label="Username",
        max_length=30,
        widget=forms.TextInput(attrs={
            'name':'username'
        })
    )
    password=forms.CharField(
        label="Password",
        max_length=32,
        widget=forms.PasswordInput()
    )

class registration_form(UserCreationForm):
    email = forms.EmailField(
        label="Email",
        required=True
        )

    class Meta:
        model = User
        fields = ("username", "email",
            "password1", "password2")

    def save(self, commit=True):
        user=super(registration_form,self).save(commit=False)
        user.email=self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class UserForm(forms.ModelForm):
   class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ('bio', 'games', 'birth_date')

CSCI465v5old/firstapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.views.generic import ListView

# from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    form = suggestion_form()
    suggestions = suggestion.objects.all().order_by('-authored')
    to_return = []
    for suggest in suggestions:
        data = {}
        data["suggestion"]=suggest.suggestion
        data["choice_field"]=suggest.choice_field
        data["image"]=suggest.image
        data["idescription"]=suggest.idescription
        data["author"]=suggest.author
        # data["comments"]=[]
        data["id"]=suggest.id
    #     comments = comment.objects.all().filter(suggestion=suggest).order_by('-authored')
    #     for comm in comments:
    #         data["comments"]+=[{"comment":comm.comment, "author":comm.author}]
    # , "comment_form":c_form
        to_return+=[data]
    context = {"suggestions":to_return, "form":form}
    return render(request,"default.html",context)


def page2(request):
    suggestions = suggestion.objects.all()
    toReturn = ""
    for sugg in suggestions:
        toReturn += sugg.suggestion + " "
    context = {"variable":toReturn}
    return render(request,"default.html",context)

def about(request):


    return render(request,"about.html")


def register(request):
    if request.method == 'POST':
        form = registration_form(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect("/")
    else:
        form = registration_form()
    context = {"form":form}
    return render(request,"register.html",context)

def lfg(request):
    form = suggestion_form()
    suggestions = suggestion.objects.filter(choice_field='LFG')
    to_return = []
    for suggest in suggestions:
        data = {}
        data["suggestion"]=suggest.suggestion
        data["choice_field"]=suggest.choice_field
        data["image"]=suggest.image
        data["idescription"]=suggest.idescription
        data["author"]=suggest.author
        data["id"]=suggest.id
        to_return+=[data]
    context = {"suggestions":to_return, "form":form}
    return render(request,"default.html",context)

def lfm(request):
    form = suggestion_form()
    suggestions = suggestion.objects.filter(choice_field='LFM')
    to_return = []
    for suggest in suggestions:
        data = {}
        data["suggestion"]=suggest.suggestion
        data["choice_field"]=suggest.choice_field
        data["image"]=suggest.image
        data["idescription"]=suggest.idescription
        data["author"]=suggest.author
        data["id"]=suggest.id
        to_return+=[data]
    context = {"suggestions":to_return, "form":form}
    return render(request,"default.html",context)

def wtb(request):
    form = suggestion_form()
    suggestions = suggestion.objects.filter(choice_field='WTB')
    to_return = []
    for suggest in suggestions:
        data = {}
        data["suggestion"]=suggest.suggestion
        data["choice_field"]=suggest.choice_field
        data["image"]=suggest.image
        data["idescription"]=suggest.idescription
        data["author"]=suggest.author
        data["id"]=suggest.id
        to_return+=[data]
    context = {"suggestions":to_return, "form":form}
    return render(request,"default.html",context)

def wts(request):
    form = suggestion_form()
    suggestions = suggestion.objects.filter(choice_field='WTS')
    to_return = []
    for suggest in suggestions:
        data = {}
        data["suggestion"]=suggest.suggestion
        data["choice_field"]=suggest.choice_field
        data["image"]=suggest.image
        data["idescription"]=suggest.idescription
        data["author"]=suggest.author
        data["id"]=suggest.id
        to_return+=[data]
    context = {"suggestions":to_return, "form":form}
    return render(request,"default.html",context)

# Source https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('.')
        # else:
        #     messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required
def suggestion_view(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = suggestion_form(request.POST, request.FILES)
            if form.is_valid():
                form.save(request)
                return redirect("/")
        else:
            form=suggestion_form()
    else:
        form = suggestion_form()
    context = {"form":form}
    return render(request,"suggest.html",context)

def suggestions(request):
    suggestions = suggestion.objects.all() #.order_by('-authored')
    toReturn = {}
    toReturn["suggestions"]=[]
    # toReturn["haha"]=[]
    for sugg in suggestions:
        toReturn["suggestions"]+=[{"suggest":sugg.suggestion}]
    return JsonResponse(toReturn)

CSCI465v5old/firstapp/templates/about.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}
{% block content %}

<div class="row column medium-9 large-7">
  <h1>About Us</h1>
  <p>This page is for all the nerds out there looking to expand their gaming circle.  Whether you need a healer for your D&D party, you're a lonely Jungilist that needs a party for League of Legends, need that last rare Magic card to finish your deck, or have a bunch of extra comics that you want to sell for some new comic money, this is the place for you.  Just make an account, then you're ready to start making posts and messaging other users.  You can use the links to browse certain posts, or just go to the home page to see all the posts.  If you have any quests, comments or concerns please direct them to HomestarRunner@Homestarrunner.net  Homestarrunner.net, it's dot com!</p>
</div>




{% endblock %}

CSCI465v5old/firstapp/templates/base.html
<!doctype html>
{% load static %}
<html class="no-js" lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
    <link rel="stylesheet" href="{% static "css/app.css" %}">

<!-- Page layout and nav bar taken from https://foundation.zurb.com/building-blocks/ -->
    <div class="app-dashboard shrink-medium">
      <div class="row expanded app-dashboard-top-nav-bar">


        <!-- Unused color changing button <button type="button" class="warning button" onclick="toggleDarkLight()">Toggle Color Scheme</button>  -->
        <header class="sticky-shrinknav-header">
          <ul class="menu align-center sticky-shrinknav-menu">
            <li>
              <div class="columns shrink app-dashboard-top-bar-actions">
                <!-- <button href="/" class="button hollow">Home</button> -->
                <a href="/" height="30" width="30" alt="">Home<i class="fa fa-info-circle"></i></a>
              </div>
            </li>
            <li>
              <div class="columns shrink app-dashboard-top-bar-actions">
                <!-- <button href="#" class="button hollow">About</button> -->
                <a href="/about/" height="30" width="30" alt="">About<i class="fa fa-info-circle"></i></a>
              </div>
            </li>
            <li>
              <div class="columns shrink app-dashboard-top-bar-actions">
                <!-- <button href="#" class="button hollow">Posts</button> -->
                <a href="/suggest/" height="30" width="30" alt="">Post<i class="fa fa-info-circle"></i></a>
              </div>
            </li>
            <li>
              <div class="columns shrink app-dashboard-top-bar-actions">
                <!-- <button href="#" class="button hollow">Messages</button> -->
                <a href="/#/" height="30" width="30" alt="">Messages<i class="fa fa-info-circle"></i></a>
              </div>
            </li>
            <li>
              <div class="columns shrink app-dashboard-top-bar-actions">
                <!-- <button href="/profile/" class="button hollow">Account</button> -->
                <a href="/profile/" height="30" width="30" alt="">Account<i class="fa fa-info-circle"></i></a>
              </div>
            </li>
            <li>
            {% if user.is_authenticated %}
            <div class="columns shrink app-dashboard-top-bar-actions">
              <!-- <button href="/logout/" class="button hollow">Logout {{ user.username }}</button> -->
              <a href="/login/" height="30" width="30" alt="">Logout {{ user.username }}<i class="fa fa-info-circle"></i></a>
            </div>
            {% else %}
            <div class="columns shrink app-dashboard-top-bar-actions">
              <!-- <button href="#" class="button hollow">Login</button> -->
              <a href="/login/" height="30" width="30" alt="">Login<i class="fa fa-info-circle"></i></a>
            </div>
            {% endif %}
            </li>
          </ul>
        </header>

      </div>

      <div class="app-dashboard-body off-canvas-wrapper">
        <div id="app-dashboard-sidebar" class="app-dashboard-sidebar position-left off-canvas off-canvas-absolute reveal-for-medium" data-off-canvas>
          <div class="app-dashboard-sidebar-title-area">
            <div class="app-dashboard-close-sidebar">
              <h3 class="app-dashboard-sidebar-block-title">Where to, traveller?</h3>
              <!-- Close button -->
              <button id="close-sidebar" data-app-dashboard-toggle-shrink class="app-dashboard-sidebar-close-button show-for-medium" aria-label="Close menu" type="button">
                <span aria-hidden="true"><a href="#"><i class="large fa fa-angle-double-left"></i></a></span>
              </button>
            </div>
            <div class="app-dashboard-open-sidebar">
              <button id="open-sidebar" data-app-dashboard-toggle-shrink class="app-dashboard-open-sidebar-button show-for-medium" aria-label="open menu" type="button">
                <span aria-hidden="true"><a href="#"><i class="large fa fa-angle-double-right"></i></a></span>
              </button>
            </div>
          </div>
          <div class="app-dashboard-sidebar-inner">
            <ul class="menu vertical">
              <li><a href="/lfg/" class="is-active">
                <i class="large fa fa-institution"></i><span class="app-dashboard-sidebar-text">LFG</span>
              </a></li>
              <li><a href="/lfm/" class="is-active">
                <i class="large fa fa-hourglass"></i><span class="app-dashboard-sidebar-text">LFM</span>
              </a></li>
              <li><a href="/wtb/" class="is-active">
                <i class="large fa fa-industry"></i><span class="app-dashboard-sidebar-text">WTB</span>
              </a></li>
              <li><a href="/wts/" class="is-active">
                <i class="large fa fa-institution"></i><span class="app-dashboard-sidebar-text">WTS</span>
              </a></li>
            </ul>
          </div>
        </div>

        <div class="app-dashboard-body-content off-canvas-content" data-off-canvas-content>


            {% block content %}{% endblock %}
            <script src="{% static "js/vendor/jquery.js" %}"></script>
            <script src="{% static "js/vendor/what-input.js" %}"></script>
            <script src="{% static "js/vendor/foundation.js" %}"></script>
            <script src="{% static "js/app.js" %}"></script>
            <script src="{% static "js/app-dashboard-layout.js" %}"></script>
            <script src="{% static "js/sticky-shrinknav.js" %}"></script>

            {% block scripts %}

            {% endblock %}
          </body>

        </div>
      </div>
    </div>


</html>

CSCI465v5old/firstapp/templates/default.html
{% extends "base.html" %}
{% load static %}

{% block title %}Title{% endblock %}
{% block content %}


<div class="grid-x grid-padding-x">
 <div class="large-8 medium-8 small-12 large-offset-2 medium-offset-2 cell">
    <h2 class="subheader text-center">Posts</h2>
    <ul style="list-style-type:none">
      {% for suggestion in suggestions %}
      <li>
        <div class="card" style="width: 600px;">


        <div class="card-divider">
          {{ suggestion.get_choice_field_display }}
        </div>
        <div class="card-divider">
        {{ suggestion.suggestion }}
      </div>
      <img src="/media/{{ suggestion.image }}"/>
      <div class="card-section">
        {{ suggestion.idescription }}
      </div>
    </div>
    {% endfor %}
  </ul>
</div>
</div>


{% endblock %}
{% block scripts %}
<script src="{% static "js/vendor/vue.js" %}"></script>
<script src="{% static "js/vueapp.js" %}"></script>
<script>
function toggleDarkLight() {
  var body = document.getElementById("body");
  var currentClass = body.className;
  body.className = currentClass == "dark-mode" ? "light-mode" : "dark-mode";
}
  //# sourceURL=harlemsquirrel.github.io/css/javascript/2017/01/31/dark-light-mode-switcher.html

</script>


{% endblock %}

CSCI465v5old/firstapp/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}
{% block content %}

<div class="grid-x grid-padding-x">
  <!-- <div class="large-4 medium-4 small-12 cell"></div> -->
  <div class="large-4 medium-4 small-12 large-offset-4 medium-offset-4 cell">
    <h2 class="text-center">Login</h2>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}

        {{ form.errors }}
        <label>{{ form.username.label_tag }}</label>
        {{ form.username }}
        <label>{{ form.password.label_tag }}</label>
        {{ form.password }}
        <input type="submit" class="button expanded" value="Login" />
        <a href="/register/" class="secondary button expanded">Register</a>
        <input type="hidden" name="next" value="/" />
    </form>
  </div>
</div>
{% endblock %}

CSCI465v5old/firstapp/templates/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}
{% block content %}
<div class="grid-x grid-padding-x">
  <!-- <div class="large-4 medium-4 small-12 cell"></div> -->
  <div class="large-6 medium-6 small-12 large-offset-3 medium-offset-3 cell">
    <h2 class="text-center">Profile</h2>
    <form method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" class="button expanded" value="Change" />
  </form>
  </div>
</div>
{% endblock %}

CSCI465v5old/firstapp/templates/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}
{% block content %}
<div class="grid-x grid-padding-x">
  <!-- <div class="large-4 medium-4 small-12 cell"></div> -->
  <div class="large-6 medium-6 small-12 large-offset-3 medium-offset-3 cell">

    <form action="/register/" method="post">
        {% csrf_token %}
        <h2 class="text-center">Register</h2>
        {{ form.errors }}
        <!-- {{form.as_p}} -->
        {{ form.username.label_tag }}
        {{ form.username }}
        {{ form.email.label_tag }}
        {{ form.email }}
        {{ form.password1.label_tag }}
        {{ form.password1 }}
        {{ form.password2.label_tag }}
        {{ form.password2 }}
        <input type="submit" class="button expanded" value="Register" />
    </form>
  </div>
</div>
{% endblock %}

CSCI465v5old/firstapp/templates/suggest.html
{% extends "base.html" %}

{% block title %}Add Suggestion{% endblock %}
{% block content %}
<div class="grid-x grid-padding-x">
  <!-- <div class="large-4 medium-4 small-12 cell"></div> -->
  <div class="large-6 medium-6 small-12 large-offset-3 medium-offset-3 cell">

    <form action="/suggest/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h4 class="text-center">Create Post</h4>
        {{ form }}
        <input type="submit" class="button expanded" value="Create Post" />
    </form>
  </div>
</div>
{% endblock %}